### ISSUE TITLE
OK gives no instead of YES

### ISSUE THREAD

**Issue by arbind** [cardmagic/classifier#25]
b = Classifier::Bayes.new "yes", "no"
b.train_yes "yes"
b.train_yes "ok"

b.train_no "no"
b.train_no "nope"
b.train_no "stop"
b.classify "ok"
# => "No"

**Comment by mauricioklein** [comment]
Same behavior here

**Comment by cardmagic** [comment]
This is because the library strips common words to try to get more signal out of the noise: https://github.com/cardmagic/classifier/blob/master/lib/classifier/extensions/word_hash.rb 

If you do a similar test and use safari animals instead of yes, no, and ok, your example works... see: https://github.com/cardmagic/classifier/pull/38
